import { OUTBOUND_STATUS } from '@/constants'

export const locations = [
    {
        id: 1,
        orderNo: '381613176',
        wmsRefNo: 'UTT-007865',
        status: 'CONFIRM',
        orderType: 'B2B',
        channel: 'Myntra',
        sla: 2,
        paymentMode: 'COD',
        orderDate: '2024-08-12 09:00',
        courier: 'HDMS',
        awbNo: 'AWB123456',
        shipToName: 'Ishaan',
        lmdStatus: 'Booked',
        orderQuantity: 15,
        zone: 'North',
        createdAt: '2024-08-12 09:15',
        createdBy: 'Amit Sharma',
        partyName: 'ABC Traders',
        partyCode: 'P12345',
        paymentStatus: 'Pending',
        updatedBy: 'Rahul Verma',
        updatedAt: '2024-08-12 10:00'
    },
    {
        id: 2,
        orderNo: '381613134',
        wmsRefNo: 'UTT-008165',
        status: 'PICKED',
        orderType: 'B2B',
        channel: 'Shopify',
        sla: 4,
        paymentMode: 'PREPAID',
        orderDate: '2024-08-12 09:00',
        courier: 'DELHIVERY',
        awbNo: 'AWB789101',
        shipToName: 'Pankaj Singh',
        lmdStatus: 'In Transit',
        orderQuantity: 12,
        zone: 'West',
        createdAt: '2024-08-12 09:20',
        createdBy: 'Priya Mehta',
        partyName: 'XYZ Enterprises',
        partyCode: 'P67890',
        paymentStatus: 'Paid',
        updatedBy: 'Sonia Kapoor',
        updatedAt: '2024-08-12 10:05'
    },
    {
        id: 3,
        orderNo: '381613200',
        wmsRefNo: 'UTT-009200',
        status: 'MANIFEST',
        orderType: 'STO',
        channel: 'Amazon',
        sla: -3,
        paymentMode: 'COD',
        orderDate: '2024-08-12 09:00',
        courier: 'BLUEDART',
        awbNo: 'AWB456789',
        shipToName: 'Rajesh Verma',
        lmdStatus: 'OFD',
        orderQuantity: 20,
        zone: 'East',
        createdAt: '2024-08-12 09:25',
        createdBy: 'Rohit Choudhary',
        partyName: 'LMN Distributors',
        partyCode: 'P24680',
        paymentStatus: 'Partially Paid',
        updatedBy: 'Neha Yadav',
        updatedAt: '2024-08-12 10:10'
    },
    {
        id: 4,
        orderNo: '381613205',
        wmsRefNo: 'UTT-009205',
        status: 'SHIPPED',
        orderType: 'Returnable Challan',
        channel: 'Flipkart',
        sla: 1,
        paymentMode: 'PREPAID',
        orderDate: '2024-08-12 09:00',
        courier: 'EKART',
        awbNo: 'AWB102938',
        shipToName: 'Anil Sharma',
        lmdStatus: 'Delivered',
        orderQuantity: 10,
        zone: 'South',
        createdAt: '2024-08-12 09:30',
        createdBy: 'Neha Kapoor',
        partyName: 'PQR Wholesalers',
        partyCode: 'P35791',
        paymentStatus: 'Pending',
        updatedBy: 'Ravi Kumar',
        updatedAt: '2024-08-12 10:15'
    },
    {
        id: 5,
        orderNo: '381613210',
        wmsRefNo: 'UTT-009210',
        status: 'MANIFEST',
        orderType: 'Non-Returnable Challan',
        channel: 'Shopify',
        sla: 18,
        paymentMode: 'COD',
        orderDate: '2024-08-12 09:00',
        courier: 'Xpressbees',
        awbNo: 'AWB564738',
        shipToName: 'Sneha Kapoor',
        lmdStatus: 'Booked',
        orderQuantity: 5,
        zone: 'North',
        createdAt: '2024-08-12 09:35',
        createdBy: 'Vikas Yadav',
        partyName: 'RST Suppliers',
        partyCode: 'P46283',
        paymentStatus: 'Paid',
        updatedBy: 'Kunal Joshi',
        updatedAt: '2024-08-12 10:20'
    },
    {
        id: 6,
        orderNo: '381613230',
        wmsRefNo: 'UTT-009230',
        status: 'MANIFEST',
        orderType: 'B2C',
        channel: 'Snapdeal',
        sla: 2,
        paymentMode: 'PREPAID',
        orderDate: '2024-08-12 09:00',
        courier: 'FEDEX',
        awbNo: 'AWB665544',
        shipToName: 'Nidhi Chauhan',
        lmdStatus: 'In Transit',
        orderQuantity: 18,
        zone: 'West',
        createdAt: '2024-08-12 09:55',
        createdBy: 'Aakash Gupta',
        partyName: 'MNO Traders',
        partyCode: 'P11223',
        paymentStatus: 'Pending',
        updatedBy: 'Meera Singh',
        updatedAt: '2024-08-12 10:45'
    },
    {
        id: 7,
        orderNo: '381613240',
        wmsRefNo: 'UTT-009240',
        status: 'SHIPPED',
        orderType: 'B2B',
        channel: 'Amazon',
        sla: 5,
        paymentMode: 'COD',
        orderDate: '2024-08-12 09:00',
        courier: 'Shadowfax',
        awbNo: 'AWB110022',
        shipToName: 'Varun Bansal',
        lmdStatus: 'Delivered',
        orderQuantity: 40,
        zone: 'North',
        createdAt: '2024-08-12 10:00',
        createdBy: 'Suresh Kumar',
        partyName: 'XYZ Exports',
        partyCode: 'P88991',
        paymentStatus: 'Paid',
        updatedBy: 'Nikita Sharma',
        updatedAt: '2024-08-12 11:00'
    },
    {
        id: 8,
        orderNo: '381613250',
        wmsRefNo: 'UTT-009250',
        status: 'PICKED',
        orderType: 'Returnable Challan',
        channel: 'Flipkart',
        sla: 7,
        paymentMode: 'PREPAID',
        orderDate: '2024-08-12 09:00',
        courier: 'EKART',
        awbNo: 'AWB998877',
        shipToName: 'Amitabh Desai',
        lmdStatus: 'OFD',
        orderQuantity: 22,
        zone: 'South',
        createdAt: '2024-08-12 10:10',
        createdBy: 'Manish Aggarwal',
        partyName: 'LMN Distributors',
        partyCode: 'P44233',
        paymentStatus: 'Partially Paid',
        updatedBy: 'Sakshi Yadav',
        updatedAt: '2024-08-12 11:15'
    },
    {
        id: 9,
        orderNo: '381613280',
        wmsRefNo: 'UTT-009280',
        status: 'PACKED',
        orderType: 'B2B',
        channel: 'Amazon',
        sla: 4,
        paymentMode: 'COD',
        orderDate: '2024-08-12 09:00',
        courier: 'Shadowfax',
        awbNo: 'AWB665577',
        shipToName: 'Rohan Malhotra',
        lmdStatus: 'OFD',
        orderQuantity: 30,
        zone: 'West',
        createdAt: '2024-08-12 10:40',
        createdBy: 'Manoj Tiwari',
        partyName: 'XYZ Logistics',
        partyCode: 'P99761',
        paymentStatus: 'Pending',
        updatedBy: 'Neha Kapoor',
        updatedAt: '2024-08-12 11:30'
    },
    {
        id: 10,
        orderNo: '381613290',
        wmsRefNo: 'UTT-009290',
        status: 'MANIFEST',
        orderType: 'Returnable Challan',
        channel: 'Flipkart',
        sla: 6,
        paymentMode: 'PREPAID',
        orderDate: '2024-08-12 09:00',
        courier: 'BlueDart',
        awbNo: 'AWB223344',
        shipToName: 'Kiran Rao',
        lmdStatus: 'Booked',
        orderQuantity: 25,
        zone: 'North',
        createdAt: '2024-08-12 10:50',
        createdBy: 'Piyush Jain',
        partyName: 'PQR Distributors',
        partyCode: 'P44322',
        paymentStatus: 'Partially Paid',
        updatedBy: 'Sanjeev Gupta',
        updatedAt: '2024-08-12 11:40'
    },
    {
        id: 11,
        orderNo: '472819200',
        wmsRefNo: 'DEL-004567',
        status: 'PICKED',
        orderType: 'B2B',
        channel: 'Amazon',
        sla: 6,
        paymentMode: 'Prepaid',
        orderDate: '2024-07-22 10:15',
        courier: 'BlueDart',
        awbNo: 'AWB123456',
        shipToName: 'Rahul Sharma',
        lmdStatus: 'In Transit',
        orderQuantity: 30,
        zone: 'North',
        createdAt: '2024-07-22 12:00',
        createdBy: 'Amit Kumar',
        partyName: 'XYZ Traders',
        partyCode: 'P55987',
        paymentStatus: 'Pending',
        updatedBy: 'Suresh Mehta',
        updatedAt: '2024-07-22 12:45'
    },
    {
        id: 12,
        orderNo: '572910321',
        wmsRefNo: 'MUM-005432',
        status: 'PACKED',
        orderType: 'B2C',
        channel: 'Flipkart',
        sla: 5,
        paymentMode: 'COD',
        orderDate: '2024-07-25 14:30',
        courier: 'DTDC',
        awbNo: 'AWB654321',
        shipToName: 'Priya Desai',
        lmdStatus: 'Created',
        orderQuantity: 20,
        zone: 'West',
        createdAt: '2024-07-25 15:00',
        createdBy: 'Sandeep Joshi',
        partyName: 'ABC Enterprises',
        partyCode: 'P66789',
        paymentStatus: 'Pending',
        updatedBy: 'Ravi Kapoor',
        updatedAt: '2024-07-25 15:40'
    }
]

export const headers = [
    {
        id: 0,
        label: 'Sr.No',
        search: false,
        sort: false,
        stick: true,
        key: 's_no',
        isFrontend: true,
        visible: true,
        minWidth: 3.1,
        maxWidth: 3.1
    },
    {
        id: 1,
        label: 'Order No',
        search: true,
        sort: true,
        key: 'order_no',
        visible: true,
        stick: true,
        minWidth: 12,
        maxWidth: 8
    },
    {
        id: 2,
        label: 'WMS Ref No',
        search: true,
        sort: true,
        key: 'external_order_id',
        visible: true,
        stick: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 3,
        label: 'Party Name',
        search: true, // new
        sort: true,
        key: 'partyName',
        visible: false,
        stick: false,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 4,
        label: 'Party code',
        search: true, // new
        sort: true,
        key: 'partyCode',
        visible: false,
        stick: false,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 5,
        label: 'Order Quantity',
        search: true,
        sort: true,
        key: 'total_qty',
        visible: true,
        stick: false,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 6,
        label: 'Order Date',
        search: true,
        sort: true,
        key: 'order_date',
        visible: true,
        stick: false,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 7,
        label: 'Fulfillment Status',
        search: false,
        sort: false,
        filter: true,
        options: Object.values(OUTBOUND_STATUS),
        key: 'status',
        visible: true,
        stick: false,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 8,
        label: 'Order Type',
        search: false,
        sort: false,
        filter: true,
        options: ['B2B', 'STO', 'Returnable Challan', 'Non-Returnable Challan', 'Purchase Return', 'Job Work'],
        key: 'orderType',
        align: 'center',
        visible: true,
        stick: false,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 9,
        label: 'Payment Status', // new
        search: false,
        sort: false,
        filter: true,
        options: ['Pending', 'Partially Paid', 'Paid'],
        key: 'paymentStatus',
        orderDate: '2024-08-12 09:00',
        visible: true,
        stick: false,
        minWidth: 9,
        maxWidth: 9
    },
    {
        id: 10,
        label: 'Channel Name',
        search: true,
        sort: true,
        key: 'channel_code',
        visible: true,
        stick: false,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 11,
        label: 'SLA',
        search: false,
        sort: false,
        filter: true,
        options: ['0-2 hrs', '2-4 hrs', '4-10 hrs', '10-24hr', '24hr+', 'SLA Breached'],
        key: 'sla',
        visible: true,
        singleSelect: true,
        stick: false,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 12,
        label: 'Courier Name',
        search: true,
        sort: true,
        key: 'courier_code',
        visible: true,
        stick: false,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 13,
        label: 'AWB No.',
        search: true,
        sort: true,
        key: 'tracking_no',
        visible: true,
        stick: false,
        minWidth: 8,
        maxWidth: 8
    },
    // {
    //     id: 8,
    //     label: 'Payment Mode',
    //     search: false,
    //     sort: false,
    //     filter: true,
    //     options: ['COD', 'PREPAID'],
    //     key: 'paymentMode',
    //     orderDate: '2024-08-12 09:00',
    //     visible: true,
    //     stick: false,
    //     minWidth: 8,
    //     maxWidth: 8
    // },
    // {
    //     id: 11,
    //     label: 'Ship to Name',
    //     search: true,
    //     sort: true,
    //     key: 'shipToName',
    //     visible: true,
    //     stick: false,
    //     minWidth: 8,
    //     maxWidth: 8
    // },
    {
        id: 14,
        label: 'Delivery Status',
        search: false,
        sort: false,
        filter: true,
        options: ['Created', 'Picked', 'Packed', 'In Transit', 'Out for Delivery', 'Delivered'],
        key: 'lmdStatus',
        visible: true,
        stick: false,
        minWidth: 8,
        maxWidth: 8
    },
    // {
    //     id: 13,
    //     label: 'Quantity',
    //     search: true,
    //     sort: true,
    //     key: 'quantity',
    //     visible: true,
    //     stick: false,
    //     minWidth: 8,
    //     maxWidth: 8
    // },
    {
        id: 15,
        label: 'Zone',
        search: true,
        sort: true,
        key: 'zone',
        visible: true,
        stick: false,
        align: 'center',
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 16,
        label: 'Created By',
        align: 'center',
        search: true,
        sort: true,
        stick: false,
        key: 'created_by',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 17,
        label: 'Created At',
        search: false,
        sort: true,
        key: 'createdAt',
        visible: true,
        stick: false,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 18,
        label: 'Updated By', // new
        search: true,
        sort: true,
        key: 'modified_by',
        visible: true,
        stick: false,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 19,
        label: 'Updated At', // new
        align: 'center',
        search: false,
        sort: true,
        stick: false,
        key: 'updatedAt',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    }
]
