/* eslint-disable */

export const locations = [
    {
        id: 1,
        box_id: 'Box-101',
        status: 'In Progress',
        weight: '5kg',
        dimensions: '20*15*10',
        qty_tab_B: 1,
        table_id: 'TBL-101',
        user_id: 'USR101',
        started_at: '14-11-2024 10:00',
        completed_at: '14-11-2024 10:30',
        modified_by: 'Alice',
        style_code: 'SC101',
        description: 'High quality product A',
        ean: '1111111111111',
        qty_tab_A: 2,
        brand: 'BrandA',
        colour: 'Red',
        size: 'M',
        mrp: '₹100',
        image: 'https://cdn.shopify.com/s/files/1/0870/1634/1808/files/clean-front-linen-blend-embroidered-qurta-navniv-1.jpg?v=1714462107',
        modified_at: '14-11-2024 10:30'
    },
    {
        id: 2,
        box_id: 'Box-102',
        status: 'Closed',
        weight: '4.5kg',
        dimensions: '25*18*12',
        qty_tab_B: 2,
        table_id: 'TBL-102',
        user_id: 'USR102',
        started_at: '14-11-2024 10:05',
        completed_at: '14-11-2024 10:40',
        modified_by: 'Bob',
        style_code: 'SC102',
        description: 'Durable and reliable product B',
        ean: '2222222222222',
        qty_tab_A: 5,
        brand: 'BrandB',
        colour: 'Blue',
        size: 'L',
        mrp: '₹150',
        image: 'https://sojanya.com/cdn/shop/files/SJR-LK-ChknPatta-1165-Dgreen-1.jpg?v=1716882821',
        modified_at: '14-11-2024 10:30'
    },
    {
        id: 3,
        box_id: 'Box-103',
        status: 'Closed',
        weight: '6kg',
        dimensions: '30*20*15',
        qty_tab_B: 3,
        table_id: 'TBL-103',
        user_id: 'USR103',
        started_at: '14-11-2024 10:10',
        completed_at: '14-11-2024 10:45',
        modified_by: 'Charlie',
        style_code: 'SC103',
        description: 'Innovative design product C',
        ean: '3333333333333',
        qty_tab_A: 3,
        brand: 'BrandC',
        colour: 'Green',
        size: 'S',
        mrp: '₹200',
        image: 'https://cdn.pixabay.com/photo/2021/02/18/09/26/coca-cola-6026672_640.jpg',
        modified_at: '14-11-2024 10:30'
    },
    {
        id: 4,
        box_id: 'Box-104',
        status: 'Dispatched',
        weight: '4kg',
        dimensions: '22*16*11',
        qty_tab_B: 1,
        table_id: 'TBL-104',
        user_id: 'USR104',
        started_at: '14-11-2024 10:15',
        completed_at: '14-11-2024 10:50',
        modified_by: 'Diana',
        style_code: 'SC104',
        description: 'Eco-friendly product D',
        ean: '4444444444444',
        qty_tab_A: 2,
        brand: 'BrandD',
        colour: 'Yellow',
        size: 'XL',
        mrp: '₹120',
        image: 'https://cdn.shopify.com/s/files/1/0870/1634/1808/files/clean-front-linen-blend-embroidered-qurta-navniv-1.jpg?v=1714462107',
        modified_at: '14-11-2024 10:30'
    },
    {
        id: 5,
        box_id: 'Box-105',
        status: 'Closed',
        weight: '7kg',
        dimensions: '28*19*14',
        qty_tab_B: 4,
        table_id: 'TBL-105',
        user_id: 'USR105',
        started_at: '14-11-2024 10:20',
        completed_at: '14-11-2024 10:55',
        modified_by: 'Evan',
        style_code: 'SC105',
        description: 'Advanced product E',
        ean: '5555555555555',
        qty_tab_A: 6,
        brand: 'BrandE',
        colour: 'Black',
        size: 'M',
        mrp: '₹180',
        image: 'https://sojanya.com/cdn/shop/files/SJR-LK-ChknPatta-1165-Dgreen-1.jpg?v=1716882821',
        modified_at: '14-11-2024 10:30'
    },
    {
        id: 6,
        box_id: 'Box-106',
        status: 'In Progress',
        weight: '3.5kg',
        dimensions: '18*14*9',
        qty_tab_B: 2,
        table_id: 'TBL-106',
        user_id: 'USR106',
        started_at: '14-11-2024 10:25',
        completed_at: '14-11-2024 11:00',
        modified_by: 'Fiona',
        style_code: 'SC106',
        description: 'Compact and efficient product F',
        ean: '6666666666666',
        qty_tab_A: 2,
        brand: 'BrandF',
        colour: 'White',
        size: 'S',
        mrp: '₹130',
        image: 'https://cdn.pixabay.com/photo/2021/02/18/09/26/coca-cola-6026672_640.jpg',
        modified_at: '14-11-2024 10:30'
    },
    {
        id: 7,
        box_id: 'Box-107',
        status: 'Dispatched',
        weight: '5.5kg',
        dimensions: '24*18*13',
        qty_tab_B: 3,
        table_id: 'TBL-107',
        user_id: 'USR107',
        started_at: '14-11-2024 10:30',
        completed_at: '14-11-2024 11:05',
        modified_by: 'George',
        style_code: 'SC107',
        description: 'Reliable and sleek product G',
        ean: '7777777777777',
        qty_tab_A: 3,
        brand: 'BrandG',
        colour: 'Orange',
        size: 'L',
        mrp: '₹160',
        image: 'https://cdn/shopify.com/s/files/1/0870/1634/1808/files/clean-front-linen-blend-embroidered-qurta-navniv-1.jpg?v=1714462107',
        modified_at: '14-11-2024 10:30'
    },
    {
        id: 8,
        box_id: 'Box-108',
        status: 'Closed',
        weight: '6.5kg',
        dimensions: '26*20*15',
        qty_tab_B: 5,
        table_id: 'TBL-108',
        user_id: 'USR108',
        started_at: '14-11-2024 10:35',
        completed_at: '14-11-2024 11:10',
        modified_by: 'Hannah',
        style_code: 'SC108',
        description: 'Top performing product H',
        ean: '8888888888888',
        qty_tab_A: 1,
        brand: 'BrandH',
        colour: 'Purple',
        size: 'XL',
        mrp: '₹210',
        image: 'https://sojanya.com/cdn/shop/files/SJR-LK-ChknPatta-1165-Dgreen-1.jpg?v=1716882821',
        modified_at: '14-11-2024 10:30'
    },
    {
        id: 9,
        box_id: 'Box-109',
        status: 'In Progress',
        weight: '4.8kg',
        dimensions: '20*15*12',
        qty_tab_B: 2,
        table_id: 'TBL-109',
        user_id: 'USR109',
        started_at: '14-11-2024 10:40',
        completed_at: '14-11-2024 11:15',
        modified_by: 'Ian',
        style_code: 'SC109',
        description: 'Innovative and stylish product I',
        ean: '9999999999999',
        qty_tab_A: 1,
        brand: 'BrandI',
        colour: 'Gray',
        size: 'M',
        mrp: '₹190',
        image: 'https://cdn.pixabay.com/photo/2021/02/18/09/26/coca-cola-6026672_640.jpg',
        modified_at: '14-11-2024 10:30'
    },
    {
        id: 10,
        box_id: 'Box-110',
        status: 'In Progress',
        weight: '5.2kg',
        dimensions: '22*17*11',
        qty_tab_B: 3,
        table_id: 'TBL-110',
        user_id: 'USR110',
        started_at: '14-11-2024 10:45',
        completed_at: '14-11-2024 11:20',
        modified_by: 'Jane',
        style_code: 'SC110',
        description: 'High performance product J',
        ean: '1010101010101',
        qty_tab_A: 4,
        brand: 'BrandJ',
        colour: 'Teal',
        size: 'L',
        mrp: '₹170',
        image: 'https://cdn/shopify.com/s/files/1/0870/1634/1808/files/clean-front-linen-blend-embroidered-qurta-navniv-1.jpg?v=1714462107',
        modified_at: '14-11-2024 10:30'
    }
]

export const headers = [
    {
        id: 0,
        label: 'Sr. No.',
        key: 's_no',
        isFrontend: true,
        search: false,
        sort: false,
        stick: true,
        visible: true,
        minWidth: 3.25,
        maxWidth: 3.25
    },
    {
        id: 1,
        label: 'Box Id',
        key: 'boxid',
        search: true,
        sort: true,
        stick: true,
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 20,
        label: 'Status',
        key: 'status',
        search: false,
        sort: false,
        filter: true,
        // options: ['In Progress', 'Closed', 'Ready For Dispatch', 'Dispatched'],
        options: ['OPEN', 'CLOSED'],
        stick: true,
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 2,
        label: 'Weight',
        key: 'actual_weight',
        search: true,
        sort: true,
        stick: false,
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 3,
        label: 'L*B*H',
        key: 'dimensions',
        search: true,
        sort: true,
        stick: false,
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 4,
        label: 'Qty',
        key: 'quantity_total',
        align: 'center',
        search: true,
        sort: true,
        stick: false,
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 5,
        label: 'Table Id',
        key: 'table_no',
        search: true,
        sort: true,
        stick: false,
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 6,
        label: 'User Id',
        key: 'created_by',
        search: true,
        sort: true,
        stick: false,
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 7,
        label: 'Started At',
        key: 'box_start_at',
        search: true,
        sort: true,
        stick: false,
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 8,
        label: 'Completed At',
        key: 'box_closed_at',
        search: true,
        sort: true,
        stick: false,
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 9,
        label: 'Modified By',
        key: 'modified_by',
        search: true,
        sort: true,
        stick: false,
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 10,
        label: 'Modified At',
        key: 'updated_at',
        search: true,
        sort: true,
        stick: false,
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    // {
    //     id: 11,
    //     label: 'Style Code',
    //     key: 'style_code',
    //     search: true,
    //     sort: true,
    //     stick: true,
    //     visible: true,
    //     minWidth: 8,
    //     maxWidth: 8
    // },
    {
        id: 18,
        label: 'Image',
        key: 'image',
        search: false,
        sort: false,
        stick: false,
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 12,
        label: 'Description',
        key: 'description',
        search: true,
        sort: true,
        stick: false,
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 13,
        label: 'EAN',
        key: 'item_no',
        search: true,
        sort: true,
        stick: false,
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 19,
        label: 'Qty',
        key: 'total_quantity',
        align: 'center',
        search: true,
        sort: true,
        stick: false,
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 14,
        label: 'Brand',
        key: 'brand',
        search: true,
        sort: true,
        stick: false,
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 15,
        label: 'Colour',
        key: 'colour',
        search: true,
        sort: true,
        stick: false,
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 16,
        label: 'Size',
        key: 'size',
        align: 'center',
        search: true,
        sort: true,
        stick: false,
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 17,
        label: 'MRP',
        key: 'mrp_price',
        align: 'center',
        search: true,
        sort: true,
        stick: false,
        visible: true,
        minWidth: 8,
        maxWidth: 8
    }
]
