/* eslint-disable */

import ArrowButton from "@core/components/arrowbutton/ArrowButton";


// using this as dummy column data
export const usersDummyData = [
    {
        id:1,
        name:'India',
        code: 'IN',
        population: 1393409038,
        size: 3287263,
        density: 423.8,
        capital: 'New Delhi',
        status: <ArrowButton label="In Progress" variant={"blue"}/> ,
        currency: 'INR',
        continent: 'Asia',
        gdp: 2875.14, // in billion USD
        lifeExpectancy: 69.7,
        literacyRate: 74.04,
        timezone: 'IST',
        officialLanguage: 'Hindi',
        internetUsers: 687000000
    },
    {
        id:2,
        name: 'United States',
        code: 'US',
        population: 331002651,
        size: 9833520,
        density: 33.7,
        capital: 'Washington, D.C.',
        status: <ArrowButton label="Completed" variant={"green"}/> ,
        currency: 'USD',
        continent: 'North America',
        gdp: 21433.22, // in billion USD
        lifeExpectancy: 78.5,
        literacyRate: 99,
        timezone: 'EST',
        officialLanguage: 'English',
        internetUsers: 287000000
    },
    {
        id:3,
        name: 'China',
        code: 'CN',
        population: 1444216107,
        size: 9596961,
        density: 150.5,
        capital: 'Beijing- A Too Long String Example To Check Tooltip',
        status: <ArrowButton label="In Progress" variant={"blue"}/> ,
        currency: 'CNY',
        continent: 'Asia',
        gdp: 14342.9, // in billion USD
        lifeExpectancy: 76.9,
        literacyRate: 96.8,
        timezone: 'CST',
        officialLanguage: 'Mandarin',
        internetUsers: 900000000
    },
    {
        id:4,
        name: 'Brazil',
        code: 'BR',
        population: 212559417,
        size: 8515767,
        density: 24.9,
        capital: 'Brasília',
        status: <ArrowButton label="Completed" variant={"green"}/> ,
        currency: 'BRL',
        continent: 'South America',
        gdp: 1839.76, // in billion USD
        lifeExpectancy: 75.7,
        literacyRate: 93.2,
        timezone: 'BRT',
        officialLanguage: 'Portuguese',
        internetUsers: 150000000
    },
    {
        id:5,
        name: 'Australia',
        code: 'AU',
        population: 25687041,
        size: 7692024,
        density: 3.3,
        capital: 'Canberra',
        status: <ArrowButton label="In Progress" variant={"blue"}/> ,
        currency: 'AUD',
        continent: 'Oceania',
        gdp: 1392.68, // in billion USD
        lifeExpectancy: 82.8,
        literacyRate: 99,
        timezone: 'AEST',
        officialLanguage: 'English',
        internetUsers: 22000000
    },
    {
        id:6,
        name: 'Russia',
        code: 'RU',
        population: 145912025,
        size: 17098242,
        density: 8.5,
        capital: 'Moscow',
        status: <ArrowButton label="In Progress" variant={"blue"}/> ,
        currency: 'RUB',
        continent: 'Europe/Asia',
        gdp: 1699.88, // in billion USD
        lifeExpectancy: 73.2,
        literacyRate: 99.7,
        timezone: 'MSK',
        officialLanguage: 'Russian',
        internetUsers: 110000000
    },
    {
        id:7,
        name: 'Japan',
        code: 'JP',
        population: 125960000,
        size: 377975,
        density: 333.3,
        capital: 'Tokyo',
        status: <ArrowButton label="Completed" variant={"green"}/> ,
        currency: 'JPY',
        continent: 'Asia',
        gdp: 5081.77, // in billion USD
        lifeExpectancy: 84.6,
        literacyRate: 99,
        timezone: 'JST',
        officialLanguage: 'Japanese',
        internetUsers: 118000000
    },
    {
        id:8,
        name: 'Germany',
        code: 'DE',
        population: 83783942,
        size: 357022,
        density: 234.7,
        capital: 'Berlin',
        status: <ArrowButton label="In Progress" variant={"blue"}/> ,
        currency: 'EUR',
        continent: 'Europe',
        gdp: 3861.12, // in billion USD
        lifeExpectancy: 81.2,
        literacyRate: 99,
        timezone: 'CET',
        officialLanguage: 'German',
        internetUsers: 82000000
    },
    {
        id: 9,
        name: 'Pakistan',
        code: 'PK',
        population: 233500636, 
        size: 881913, 
        density: 265, 
        capital: 'Islamabad',
        status: <ArrowButton label="In Progress" variant={"blue"}/> ,
        currency: 'PKR',
        continent: 'Asia',
        gdp: 346.34, // in billion USD
        lifeExpectancy: 67.3,
        literacyRate: 59,
        timezone: 'PKT',
        officialLanguage: 'Urdu',
        internetUsers: 123000000
    },
    {
        id: 10,
        name: 'Bangladesh',
        code: 'BD',
        population: 169356251, 
        size: 148460, 
        density: 1140, 
        capital: 'Dhaka',
        status: <ArrowButton label="Completed" variant={"green"}/> ,
        currency: 'BDT',
        continent: 'Asia',
        gdp: 409.2, // in billion USD
        lifeExpectancy: 72.6,
        literacyRate: 74,
        timezone: 'BST',
        officialLanguage: 'Bengali',
        internetUsers: 120000000
    },
    {
        id: 11,
        name: 'Chile',
        code: 'CL',
        population: 19212362,
        size: 756102,
        density: 25,
        capital: 'Santiago',
        status: <ArrowButton label="In Progress" variant={"blue"}/>,
        currency: 'CLP',
        continent: 'South America',
        gdp: 317.05, // in billion USD
        lifeExpectancy: 80.2,
        literacyRate: 96,
        timezone: 'CLT',
        officialLanguage: 'Spanish',
        internetUsers: 16000000
    },
    {
        id: 12,
        name: 'Poland',
        code: 'PL',
        population: 37958138,
        size: 312696,
        density: 121,
        capital: 'Warsaw',
        status: <ArrowButton label="Completed" variant={"green"}/>,
        currency: 'PLN',
        continent: 'Europe',
        gdp: 679.41, // in billion USD
        lifeExpectancy: 78.5,
        literacyRate: 99,
        timezone: 'CET',
        officialLanguage: 'Polish',
        internetUsers: 28900000
    },
    {
        id: 13,
        name: 'Bhutan',
        code: 'BT',
        population: 777486,
        size: 38394,
        density: 20,
        capital: 'Thimphu',
        status: <ArrowButton label="In Progress" variant={"blue"}/>,
        currency: 'BTN',
        continent: 'Asia',
        gdp: 2.84, // in billion USD
        lifeExpectancy: 71.8,
        literacyRate: 66,
        timezone: 'BTT',
        officialLanguage: 'Dzongkha',
        internetUsers: 520000
    },
    {
        id: 14,
        name: 'Sri Lanka',
        code: 'LK',
        population: 21413249,
        size: 65610,
        density: 326,
        capital: 'Sri Jayawardenepura Kotte',
        status: <ArrowButton label="Completed" variant={"green"}/>,
        currency: 'LKR',
        continent: 'Asia',
        gdp: 84.52, // in billion USD
        lifeExpectancy: 76.4,
        literacyRate: 92,
        timezone: 'SLST',
        officialLanguage: 'Sinhala, Tamil',
        internetUsers: 10900000
    },
    {
        id: 15,
        name: 'Bhutan',
        code: 'BT',
        population: 777486,
        size: 38394,
        density: 20,
        capital: 'Thimphu',
        status: <ArrowButton label="In Progress" variant={"blue"}/>,
        currency: 'BTN',
        continent: 'Asia',
        gdp: 2.84, // in billion USD
        lifeExpectancy: 71.8,
        literacyRate: 66,
        timezone: 'BTT',
        officialLanguage: 'Dzongkha',
        internetUsers: 520000
    },
    {
        id: 16,
        name: 'Bhutan',
        code: 'BT',
        population: 777486,
        size: 38394,
        density: 20,
        capital: 'Thimphu',
        status: <ArrowButton label="In Progress" variant={"blue"}/>,
        currency: 'BTN',
        continent: 'Asia',
        gdp: 2.84, // in billion USD
        lifeExpectancy: 71.8,
        literacyRate: 66,
        timezone: 'BTT',
        officialLanguage: 'Dzongkha',
        internetUsers: 520000
    },  
    {
        id: 11,
        name: 'Chile',
        code: 'CL',
        population: 19212362,
        size: 756102,
        density: 25,
        capital: 'Santiago',
        status: <ArrowButton label="In Progress" variant={"blue"}/>,
        currency: 'CLP',
        continent: 'South America',
        gdp: 317.05, // in billion USD
        lifeExpectancy: 80.2,
        literacyRate: 96,
        timezone: 'CLT',
        officialLanguage: 'Spanish',
        internetUsers: 16000000
    },
    {
        id: 12,
        name: 'Poland',
        code: 'PL',
        population: 37958138,
        size: 312696,
        density: 121,
        capital: 'Warsaw',
        status: <ArrowButton label="Completed" variant={"green"}/>,
        currency: 'PLN',
        continent: 'Europe',
        gdp: 679.41, // in billion USD
        lifeExpectancy: 78.5,
        literacyRate: 99,
        timezone: 'CET',
        officialLanguage: 'Polish',
        internetUsers: 28900000
    },
    {
        id: 13,
        name: 'Bhutan',
        code: 'BT',
        population: 777486,
        size: 38394,
        density: 20,
        capital: 'Thimphu',
        status: <ArrowButton label="In Progress" variant={"blue"}/>,
        currency: 'BTN',
        continent: 'Asia',
        gdp: 2.84, // in billion USD
        lifeExpectancy: 71.8,
        literacyRate: 66,
        timezone: 'BTT',
        officialLanguage: 'Dzongkha',
        internetUsers: 520000
    },
    {
        id: 14,
        name: 'Sri Lanka',
        code: 'LK',
        population: 21413249,
        size: 65610,
        density: 326,
        capital: 'Sri Jayawardenepura Kotte',
        status: <ArrowButton label="Completed" variant={"green"}/>,
        currency: 'LKR',
        continent: 'Asia',
        gdp: 84.52, // in billion USD
        lifeExpectancy: 76.4,
        literacyRate: 92,
        timezone: 'SLST',
        officialLanguage: 'Sinhala, Tamil',
        internetUsers: 10900000
    },
    {
        id: 15,
        name: 'Bhutan',
        code: 'BT',
        population: 777486,
        size: 38394,
        density: 20,
        capital: 'Thimphu',
        status: <ArrowButton label="In Progress" variant={"blue"}/>,
        currency: 'BTN',
        continent: 'Asia',
        gdp: 2.84, // in billion USD
        lifeExpectancy: 71.8,
        literacyRate: 66,
        timezone: 'BTT',
        officialLanguage: 'Dzongkha',
        internetUsers: 520000
    },
    {
        id: 16,
        name: 'Bhutan',
        code: 'BT',
        population: 777486,
        size: 38394,
        density: 20,
        capital: 'Thimphu',
        status: <ArrowButton label="In Progress" variant={"blue"}/>,
        currency: 'BTN',
        continent: 'Asia',
        gdp: 2.84, // in billion USD
        lifeExpectancy: 71.8,
        literacyRate: 66,
        timezone: 'BTT',
        officialLanguage: 'Dzongkha',
        internetUsers: 520000
    }  
];
