export const locations = [
    {
        id: 1,
        orderId: 'VYP049008',
        packId: 'PKID-01',
        orderType: 'B2B',
        status: 'Part Packed',
        channel: 'Flipkart',
        sla: 1,
        orderQty: 100,
        packedQty: 65,
        pendingQty: 35,
        orderDate: '12/08/2025'
    },
    {
        id: 2,
        orderId: 'VYP049009',
        packId: 'PKID-02',
        orderType: 'B2C',
        status: 'Part Packed',
        channel: 'Amazon',
        sla: 4,
        orderQty: 250,
        packedQty: 240,
        pendingQty: 10,
        orderDate: '12/08/2025'
    },
    {
        id: 3,
        orderId: 'VYP049010',
        packId: '',
        orderType: 'STO',
        status: 'Part Picked',
        channel: 'Myntra',
        sla: -1,
        orderQty: 80,
        packedQty: 0,
        pendingQty: 80,
        orderDate: '12/08/2025'
    },
    {
        id: 4,
        orderId: 'VYP049011',
        packId: 'PKID-04',
        orderType: 'Returnable Challan',
        status: 'Part Packed',
        channel: 'Flipkart',
        sla: 8,
        orderQty: 150,
        packedQty: 100,
        pendingQty: 50,
        orderDate: '12/08/2025'
    },
    {
        id: 5,
        orderId: 'VYP049012',
        packId: 'PKID-05',
        orderType: 'B2C',
        status: 'Part Packed',
        channel: 'Amazon',
        sla: 1,
        orderQty: 300,
        packedQty: 180,
        pendingQty: 120,
        orderDate: '12/08/2025'
    },
    {
        id: 6,
        orderId: 'VYP049013',
        packId: '',
        orderType: 'Purchase Return',
        status: 'Picked',
        channel: 'Myntra',
        sla: 4,
        orderQty: 75,
        packedQty: 0,
        pendingQty: 75,
        orderDate: '12/08/2025'
    },
    {
        id: 7,
        orderId: 'VYP049014',
        packId: 'PKID-07',
        orderType: 'B2B',
        status: 'Part Packed',
        channel: 'Flipkart',
        sla: -1,
        orderQty: 200,
        packedQty: 164,
        pendingQty: 36,
        orderDate: '12/08/2025'
    },
    {
        id: 8,
        orderId: 'VYP049015',
        packId: 'PKID-08',
        orderType: 'Job Work',
        status: 'Part Packed',
        channel: 'Amazon',
        sla: 8,
        orderQty: 120,
        packedQty: 90,
        pendingQty: 30,
        orderDate: '12/08/2025'
    },
    {
        id: 9,
        orderId: 'VYP049016',
        packId: 'PKID-09',
        orderType: 'Exchange',
        status: 'Part Packed',
        channel: 'Myntra',
        sla: 1,
        orderQty: 50,
        packedQty: 15,
        pendingQty: 35,
        orderDate: '12/08/2025'
    },
    {
        id: 10,
        orderId: 'VYP049017',
        packId: 'PKID-10',
        orderType: 'Non-Returnable Challan',
        status: 'Part Packed',
        channel: 'Flipkart',
        sla: 4,
        orderQty: 180,
        packedQty: 80,
        pendingQty: 100,
        orderDate: '12/08/2025'
    },
    {
        id: 11,
        orderId: 'VYP049018',
        packId: 'PKID-11',
        orderType: 'Sample',
        status: 'Part Packed',
        channel: 'Amazon',
        sla: -1,
        orderQty: 25,
        packedQty: 10,
        pendingQty: 15,
        orderDate: '12/08/2025'
    },
    {
        id: 12,
        orderId: 'VYP049019',
        packId: 'PKID-12',
        orderType: 'Promotion',
        status: 'Part Packed',
        channel: 'Myntra',
        sla: 8,
        orderQty: 400,
        packedQty: 320,
        pendingQty: 80,
        orderDate: '12/08/2025'
    }
]

export const headers = [
    {
        id: 0,
        label: 'Sr. No.',
        search: false,
        sort: false,
        stick: true,
        key: 'id',
        visible: true,
        minWidth: 3.25,
        maxWidth: 3.25
    },
    {
        id: 2,
        label: 'Order Id',
        search: true,
        sort: true,
        key: 'orderId',
        visible: true,
        stick: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 1,
        label: 'Pack Id',
        search: true,
        sort: true,
        key: 'packId',
        visible: true,
        stick: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 3,
        label: 'Order Date',
        search: true,
        sort: true,
        key: 'orderDate',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 4,
        label: 'Order Type',
        search: false,
        sort: false,
        filter: true,
        options: [
            'B2B',
            'STO',
            'Returnable Challan',
            'Non-Returnable Challan',
            'Purchase Return',
            'Job Work',
            'B2C',
            'Exchange',
            'Sample',
            'Promotion'
        ],
        key: 'orderType',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 7,
        label: 'SLA',
        search: false,
        sort: false,
        filter: true,
        options: ['0-2 hrs', '2-4 hrs', '4-10 hrs', '10-24hr', '24hr+', 'SLA Breached'],
        key: 'sla',
        visible: true,
        singleSelect: true,
        stick: false,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 8,
        label: 'Order Qty',
        search: false,
        sort: true,
        key: 'orderQty',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 9,
        label: 'Packed Qty',
        search: false,
        sort: true,
        key: 'packedQty',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 10,
        label: 'Pending Qty',
        search: false,
        sort: true,
        key: 'pendingQty',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 5,
        label: 'Channel',
        search: true,
        sort: true,
        key: 'channel',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 6,
        label: 'Order Status',
        search: false,
        sort: false,
        filter: true,
        options: ['Picked', 'Part Picked', 'Part Packed'],
        key: 'status',
        visible: true,
        stick: false,
        minWidth: 8,
        maxWidth: 8
    }
]
