/* eslint-disable */

export const locations = [
    {
        id: 1,
        purchaseOrderNo: 'CRP/001',
        vendorName: 'Piyush & Sons',
        vendorCode: 'Vend/001',
        wmsRefNo: 'PO/001',
        totalQty: 100,
        receivedQty: 99,
        pendingQty: 1,
        createdBy: 'Rohit Singh',
        createdAt: '12-08-2024 09:15',
        modifiedBy: 'Sneha Verma',
        modifiedAt: '14-10-2024 14:32'
    },
    {
        id: 2,
        purchaseOrderNo: 'CRP/002',
        vendorName: 'Pankaj Limited',
        vendorCode: 'Vend/002',
        wmsRefNo: 'PO/002',
        totalQty: 100,
        receivedQty: 100,
        pendingQty: 0,
        createdBy: 'Rohit Singh',
        createdAt: '12-08-2024 09:20',
        modifiedBy: 'Sneha Verma',
        modifiedAt: '14-10-2024 14:40'
    },
    {
        id: 3,
        purchaseOrderNo: 'CRP/003',
        vendorName: 'Rizwan Technologies',
        vendorCode: 'Vend/003',
        wmsRefNo: 'PO/003',
        totalQty: 100,
        receivedQty: 0,
        pendingQty: 100,
        createdBy: 'Rohit Singh',
        createdAt: '12-08-2024 09:25',
        modifiedBy: 'Sneha Verma',
        modifiedAt: '14-10-2024 14:45'
    },
    {
        id: 4,
        purchaseOrderNo: 'CRP/004',
        vendorName: 'Kausik Pvt Ltd',
        vendorCode: 'Vend/004',
        wmsRefNo: 'PO/004',
        totalQty: 100,
        receivedQty: 45,
        pendingQty: 55,
        createdBy: 'Rohit Singh',
        createdAt: '12-08-2024 09:30',
        modifiedBy: 'Sneha Verma',
        modifiedAt: '14-10-2024 14:50'
    },
    {
        id: 5,
        purchaseOrderNo: 'CRP/005',
        vendorName: 'Mahesh Enterprises',
        vendorCode: 'Vend/005',
        wmsRefNo: 'PO/005',
        totalQty: 100,
        receivedQty: 80,
        pendingQty: 20,
        createdBy: 'Rohit Singh',
        createdAt: '12-08-2024 09:35',
        modifiedBy: 'Sneha Verma',
        modifiedAt: '14-10-2024 14:55'
    },
    {
        id: 6,
        purchaseOrderNo: 'CRP/006',
        vendorName: 'Anil Traders',
        vendorCode: 'Vend/006',
        wmsRefNo: 'PO/006',
        totalQty: 100,
        receivedQty: 90,
        pendingQty: 10,
        createdBy: 'Rohit Singh',
        createdAt: '12-08-2024 09:40',
        modifiedBy: 'Sneha Verma',
        modifiedAt: '14-10-2024 15:00'
    },
    {
        id: 7,
        purchaseOrderNo: 'CRP/007',
        vendorName: 'Sharma Supplies',
        vendorCode: 'Vend/007',
        wmsRefNo: 'PO/007',
        totalQty: 100,
        receivedQty: 70,
        pendingQty: 30,
        createdBy: 'Rohit Singh',
        createdAt: '12-08-2024 09:45',
        modifiedBy: 'Sneha Verma',
        modifiedAt: '14-10-2024 15:05'
    },
    {
        id: 8,
        purchaseOrderNo: 'CRP/008',
        vendorName: 'Gupta Distributors',
        vendorCode: 'Vend/008',
        wmsRefNo: 'PO/008',
        totalQty: 100,
        receivedQty: 60,
        pendingQty: 40,
        createdBy: 'Rohit Singh',
        createdAt: '12-08-2024 09:50',
        modifiedBy: 'Sneha Verma',
        modifiedAt: '14-10-2024 15:10'
    },
    {
        id: 9,
        purchaseOrderNo: 'CRP/009',
        vendorName: 'Verma Exports',
        vendorCode: 'Vend/009',
        wmsRefNo: 'PO/009',
        totalQty: 100,
        receivedQty: 85,
        pendingQty: 15,
        createdBy: 'Rohit Singh',
        createdAt: '12-08-2024 09:55',
        modifiedBy: 'Sneha Verma',
        modifiedAt: '14-10-2024 15:15'
    },
    {
        id: 10,
        purchaseOrderNo: 'CRP/010',
        vendorName: 'Rajesh Industries',
        vendorCode: 'Vend/010',
        wmsRefNo: 'PO/010',
        totalQty: 100,
        receivedQty: 50,
        pendingQty: 50,
        createdBy: 'Rohit Singh',
        createdAt: '12-08-2024 10:00',
        modifiedBy: 'Sneha Verma',
        modifiedAt: '14-10-2024 15:20'
    }
]

export const headers = [
    {
        id: 0,
        label: 'Sr.No.',
        search: false,
        sort: false,
        stick: true,
        key: 's_no',
        isFrontend: true,
        visible: true,
        minWidth: 3.18,
        maxWidth: 3.18,
        align: 'center'
    },
    {
        id: 1,
        label: 'Purchase Order No.',
        search: true,
        sort: false,
        stick: true,
        key: 'no',
        visible: true,
        minWidth: 8.76,
        maxWidth: 8.76
    },
    {
        id: 12,
        label: 'Vendor Name',
        search: true,
        sort: false,
        stick: true,
        key: 'vendor_name',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 13,
        label: 'Vendor Code',
        search: true,
        sort: false,
        stick: true,
        key: 'vendor_code',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 2,
        // label: 'WMS Ref No', // don't know if it's correct !confirm!
        label: 'External PO No', // confirmed it with Ishaan sir
        search: true,
        sort: false,
        align: 'left',
        stick: false,
        key: 'ext_po_no',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 6,
        label: 'Status',
        search: false,
        sort: false,
        stick: false,
        key: 'status',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 14,
        label: 'Total Qty',
        search: false,
        sort: false,
        stick: false,
        key: 'total_quantity',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 16,
        label: 'Received Qty',
        search: false,
        sort: false,
        stick: false,
        key: 'received_quantity',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 17,
        label: 'Pending Qty',
        search: false,
        sort: false,
        stick: false,
        key: 'pending_quantity',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    // {
    //     id: 3,
    //     label: 'rfq/ref_no',
    //     search: false,
    //     sort: false,
    //     stick: false,
    //     key: 'rfq/ref_no',
    //     visible: true,
    //     minWidth: 8,
    //     maxWidth: 8
    // },
    // {
    //     id: 4,
    //     label: 'po_type',
    //     search: false,
    //     sort: false,
    //     stick: false,
    //     key: 'po_type',
    //     visible: true,
    //     minWidth: 8,
    //     maxWidth: 8
    // },
    // {
    //     id: 5,
    //     label: 'client_id',
    //     search: false,
    //     sort: false,
    //     stick: false,
    //     key: 'client_id',
    //     visible: true,
    //     minWidth: 8,
    //     maxWidth: 8
    // },
    // {
    //     id: 6,
    //     label: 'location_code',
    //     search: false,
    //     sort: false,
    //     stick: false,
    //     key: 'location_code',
    //     visible: true,
    //     minWidth: 8,
    //     maxWidth: 8
    // },
    // {
    //     id: 7,
    //     label: 'vendor_id',
    //     search: false,
    //     sort: false,
    //     stick: false,
    //     key: 'vendor_id',
    //     visible: true,
    //     minWidth: 8,
    //     maxWidth: 8
    // },
    // {
    //     id: 9,
    //     label: 'order_date',
    //     search: false,
    //     sort: false,
    //     stick: false,
    //     key: 'order_date',
    //     visible: true,
    //     minWidth: 8,
    //     maxWidth: 8
    // },
    // {
    //     id: 10,
    //     label: 'expiry_date',
    //     search: false,
    //     sort: false,
    //     stick: false,
    //     key: 'expiry_date',
    //     visible: true,
    //     minWidth: 8,
    //     maxWidth: 8
    // },
    // {
    //     id: 11,
    //     label: 'edd',
    //     search: false,
    //     sort: false,
    //     stick: false,
    //     key: 'edd',
    //     visible: true,
    //     minWidth: 8,
    //     maxWidth: 8
    // },
    // {
    //     id: 12,
    //     label: 'transport_method',
    //     search: false,
    //     sort: false,
    //     stick: false,
    //     key: 'transport_method',
    //     visible: true,
    //     minWidth: 8,
    //     maxWidth: 8
    // },
    // {
    //     id: 13,
    //     label: 'status',
    //     search: false,
    //     sort: false,
    //     stick: false,
    //     key: 'status',
    //     visible: true,
    //     minWidth: 8,
    //     maxWidth: 8
    // },
    // {
    //     id: 15,
    //     label: 'remaining_quantity',
    //     search: false,
    //     sort: false,
    //     stick: false,
    //     key: 'remaining_quantity',
    //     visible: true,
    //     minWidth: 8,
    //     maxWidth: 8
    // },
    {
        id: 4,
        label: 'Created By',
        search: true,
        sort: false,
        stick: false,
        key: 'created_by',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 5,
        label: 'Created At',
        search: true,
        sort: true,
        stick: false,
        key: 'created_at',
        visible: true,
        minWidth: 10,
        maxWidth: 10
    },
    {
        id: 7,
        label: 'Modified By',
        search: true,
        sort: false,
        stick: false,
        key: 'modified_by',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 8,
        label: 'Modified At',
        search: false,
        sort: true,
        stick: false,
        key: 'updated_at',
        visible: true,
        minWidth: 10,
        maxWidth: 10
    }
]
