export const locations = [
    {
        id: 1,
        GENo: 'GE/001',
        invoiceNo: 'INV/001',
        status: 'Completed',
        vendorCode: 'V001',
        vendorName: 'Piyush & Sons',
        totalExpectedQty: 100,
        totalPendingQty: 10,
        docType: 'PO',
        documentNo: 'DOC/001',
        GRN: 'GRN/001',
        noOfCases: 20,
        lrDoc: null,
        invoiceDoc:
            'https://www.invoicesimple.com/wp-content/uploads/2024/08/photography-invoice-template-black-white-en.jpg',
        poNo: null,
        ewayBill: 'https://www.kladana.com/wp-content/uploads/2024/07/eway-bill-system-screenshot-1.jpg',
        createdBy: 'Rohit Singh',
        createdAt: '2024-08-12 09:15',
        modifiedBy: 'Sneha Verma',
        modifiedAt: '2024-10-14 14:32',
        vehicleReleasedAt: ''
    },
    {
        id: 2,
        GENo: 'GE/002',
        invoiceNo: 'INV/002',
        status: 'WIP',
        vendorCode: 'V002',
        vendorName: 'Raj Traders',
        totalExpectedQty: 200,
        totalPendingQty: 50,
        docType: 'ASN',
        documentNo: 'DOC/002',
        GRN: 'GRN/002',
        noOfCases: 2,
        createdBy: 'Anil Kumar',
        createdAt: '2024-08-15 11:20',
        modifiedBy: 'Nisha Sharma',
        modifiedAt: '2024-09-20 17:45',
        vehicleReleasedAt: '2024-09-20 17:45'
    },
    {
        id: 3,
        GENo: 'GE/003',
        invoiceNo: 'INV/003',
        status: 'WIP',
        vendorCode: 'V003',
        vendorName: 'Sharma Supplies',
        totalExpectedQty: 150,
        totalPendingQty: 25,
        docType: 'Direct',
        documentNo: 'DOC/003',
        GRN: 'GRN/003',
        noOfCases: 8,
        createdBy: 'Karan Mehta',
        createdAt: '2024-08-18 13:50',
        modifiedBy: 'Ritika Jain',
        modifiedAt: '2024-09-22 10:25',
        vehicleReleasedAt: ''
    },
    {
        id: 4,
        GENo: 'GE/004',
        invoiceNo: 'INV/004',
        status: 'Open',
        vendorCode: 'V004',
        vendorName: 'Verma Enterprises',
        totalExpectedQty: 120,
        totalPendingQty: 60,
        docType: 'PO',
        documentNo: 'DOC/004',
        GRN: 'GRN/004',
        noOfCases: 11,
        createdBy: 'Suman Agarwal',
        createdAt: '2024-08-20 14:30',
        modifiedBy: 'Manish Tiwari',
        modifiedAt: '2024-10-10 16:00',
        vehicleReleasedAt: '2024-10-04 04:25'
    },
    {
        id: 5,
        GENo: 'GE/005',
        invoiceNo: 'INV/005',
        status: 'Open',
        vendorCode: 'V005',
        vendorName: 'Global Supplies',
        totalExpectedQty: 180,
        totalPendingQty: 20,
        docType: 'ASN',
        documentNo: 'DOC/005',
        GRN: 'GRN/005',
        noOfCases: 6,
        createdBy: 'Ravi Sharma',
        createdAt: '2024-08-25 10:45',
        modifiedBy: 'Priya Sen',
        modifiedAt: '2024-10-01 11:20',
        vehicleReleasedAt: ''
    },
    {
        id: 6,
        GENo: 'GE/006',
        invoiceNo: 'INV/006',
        status: 'Completed',
        vendorCode: 'V006',
        vendorName: 'Elite Traders',
        totalExpectedQty: 250,
        totalPendingQty: 100,
        docType: 'Direct',
        documentNo: 'DOC/006',
        GRN: 'GRN/006',
        noOfCases: 9,
        createdBy: 'Amit Das',
        createdAt: '2024-08-30 12:00',
        modifiedBy: 'Neha Gupta',
        modifiedAt: '2024-09-18 15:45',
        vehicleReleasedAt: ''
    },
    {
        id: 7,
        GENo: 'GE/007',
        invoiceNo: 'INV/007',
        status: 'Completed',
        vendorCode: 'V007',
        vendorName: 'Mitra Enterprises',
        totalExpectedQty: 300,
        totalPendingQty: 0,
        docType: 'PO',
        documentNo: 'DOC/007',
        GRN: 'GRN/007',
        noOfCases: 6,
        createdBy: 'Arjun Kapoor',
        createdAt: '2024-09-01 09:00',
        modifiedBy: 'Tanvi Singh',
        modifiedAt: '2024-10-15 12:30',
        vehicleReleasedAt: '2024-10-15 12:30'
    },
    {
        id: 8,
        GENo: 'GE/008',
        invoiceNo: 'INV/008',
        status: 'WIP',
        vendorCode: 'V008',
        vendorName: 'Bright Solutions',
        totalExpectedQty: 400,
        totalPendingQty: 120,
        docType: 'ASN',
        documentNo: 'DOC/008',
        GRN: 'GRN/008',
        noOfCases: 3,
        createdBy: 'Kunal Gupta',
        createdAt: '2024-09-05 14:10',
        modifiedBy: 'Megha Sharma',
        modifiedAt: '2024-09-30 13:55',
        vehicleReleasedAt: '2024-09-30 13:55'
    },
    {
        id: 9,
        GENo: 'GE/009',
        invoiceNo: 'INV/009',
        status: 'Open',
        vendorCode: 'V009',
        vendorName: 'Krishna Industries',
        totalExpectedQty: 500,
        totalPendingQty: 50,
        docType: 'Direct',
        documentNo: 'DOC/009',
        GRN: 'GRN/009',
        noOfCases: 9,
        createdBy: 'Alok Roy',
        createdAt: '2024-09-10 08:30',
        modifiedBy: 'Sonia Batra',
        modifiedAt: '2024-10-05 09:45',
        vehicleReleasedAt: '2024-10-05 09:45'
    },
    {
        id: 10,
        GENo: 'GE/010',
        invoiceNo: 'INV/010',
        status: 'Completed',
        vendorCode: 'V010',
        vendorName: 'Green Fields Co.',
        totalExpectedQty: 350,
        totalPendingQty: 80,
        docType: 'PO',
        documentNo: 'DOC/010',
        GRN: 'GRN/010',
        noOfCases: 13,
        createdBy: 'Isha Malhotra',
        createdAt: '2024-09-12 11:15',
        modifiedBy: 'Rahul Tandon',
        modifiedAt: '2024-10-08 10:00',
        vehicleReleasedAt: ''
    }
]

export const headers = [
    {
        id: 0,
        label: 'Sr.No',
        search: false,
        sort: false,
        stick: true,
        key: 's_no',
        isFrontend: true,
        visible: true,
        minWidth: 3.1,
        maxWidth: 3.1
    },
    {
        id: 1,
        label: 'GE.No',
        search: true,
        sort: true,
        stick: true,
        key: 'no',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 3,
        label: 'Status',
        search: true,
        sort: false,
        stick: true,
        key: 'status',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 15,
        label: 'Vendor Code',
        search: true,
        sort: false,
        stick: false,
        key: 'code',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 16,
        label: 'Vendor Name',
        search: true,
        sort: false,
        stick: false,
        key: 'name',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 4,
        label: 'Total Expected Qty',
        search: true,
        sort: true,
        stick: false,
        key: 'total_quantity',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 5,
        label: 'Total Pending Qty',
        search: true,
        sort: true,
        stick: false,
        key: 'remaining',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 6,
        label: 'Document Type',
        search: true,
        sort: false,
        stick: false,
        key: 'document_type',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 999,
        label: 'GRN',
        search: true,
        sort: true,
        stick: false,
        key: 'grn',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 9,
        label: 'Vehicle Released At',
        search: true,
        sort: true,
        stick: false,
        key: 'release_date',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 10,
        label: 'No of Cases',
        search: true,
        sort: true,
        stick: false,
        key: 'no_of_cases',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 989,
        label: 'Attachment',
        search: false,
        sort: false,
        stick: false,
        key: 'files',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 11,
        label: 'Created By',
        search: true,
        sort: false,
        stick: false,
        key: 'created_by',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 13,
        label: 'Created At',
        search: false,
        sort: true,
        stick: false,
        key: 'created_at',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 12,
        label: 'Modified By',
        search: true,
        sort: false,
        stick: false,
        key: 'modified_by',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 14,
        label: 'Modified At',
        search: false,
        sort: true,
        stick: false,
        key: 'updated_at',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    }
    // {
    //     id: 2,
    //     label: 'invoice_no',
    //     search: false,
    //     sort: false,
    //     stick: false,
    //     key: 'invoice_no',
    //     visible: true,
    //     minWidth: 8,
    //     maxWidth: 8
    // },
    // {
    //     id: 7,
    //     label: 'document_no',
    //     search: false,
    //     sort: false,
    //     stick: false,
    //     key: 'document_no',
    //     visible: true,
    //     minWidth: 8,
    //     maxWidth: 8
    // },
    // {
    //     id: 8,
    //     label: 'ext_document_no',
    //     search: false,
    //     sort: false,
    //     stick: false,
    //     key: 'ext_document_no',
    //     visible: true,
    //     minWidth: 8,
    //     maxWidth: 8
    // }
]
