export const headers = [
    {
        id: 0,
        label: 'id',
        align: 'center',
        search: false,
        sort: false,
        stick: true,
        key: 's_no',
        isFrontend: true,
        visible: true,
        minWidth: 3.1,
        maxWidth: 3.1
    },
    {
        id: 1,
        label: 'code',
        align: 'center',
        search: true,
        sort: true,
        stick: true,
        key: 'code',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 2,
        label: 'Name',
        align: 'left',
        search: true,
        sort: true,
        stick: true,
        key: 'name',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 3,
        label: 'Industry',
        align: 'left',
        search: true,
        sort: false,
        stick: true,
        key: 'industry',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 4,
        label: 'Logo',
        align: 'left',
        search: false,
        sort: false,
        stick: false,
        key: 'logo',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 5,
        label: 'Signature',
        align: 'left',
        search: false,
        sort: false,
        stick: false,
        key: 'signature',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 6,
        label: 'Billing Name', // bd_name
        align: 'center',
        search: true,
        sort: true,
        stick: false,
        key: 'bd_name',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 7,
        label: 'Billing Contact Number',
        align: 'center',
        search: true,
        sort: true,
        stick: false,
        key: 'bd_contact_number',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 8,
        label: 'Billing Email',
        align: 'center',
        search: true,
        sort: true,
        stick: false,
        key: 'bd_email',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 9,
        label: 'Billing Contact Person',
        align: 'center',
        search: true,
        sort: true,
        stick: false,
        key: 'bContactPerson',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 10,
        label: 'Billing Country',
        align: 'center',
        search: true,
        sort: true,
        stick: false,
        key: 'bcountry',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 11,
        label: 'Billing State',
        align: 'center',
        search: true,
        sort: true,
        stick: false,
        key: 'bstate',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 12,
        label: 'Billing City',
        align: 'center',
        search: true,
        sort: true,
        stick: false,
        key: 'bcity',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 13,
        label: 'Billing Post Code',
        align: 'center',
        search: true,
        sort: true,
        stick: false,
        key: 'bpostcode',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 14,
        label: 'Billing Address',
        align: 'center',
        search: true,
        sort: true,
        stick: false,
        key: 'baddress',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 15,
        label: 'Billing Address 2',
        align: 'center',
        search: true,
        sort: true,
        stick: false,
        key: 'baddress2',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 16,
        label: 'Billing Phone',
        align: 'center',
        search: true,
        sort: true,
        stick: false,
        key: 'bphone',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 17,
        label: 'Billing Email',
        align: 'center',
        search: true,
        sort: true,
        stick: false,
        key: 'bemail',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 18,
        label: 'TAT No',
        align: 'center',
        search: true,
        sort: true,
        stick: false,
        key: 'tat_no',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 19,
        label: 'Pan No',
        align: 'center',
        search: true,
        sort: true,
        stick: false,
        key: 'pan_no',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 20,
        label: 'TIN No',
        align: 'center',
        search: true,
        sort: true,
        stick: false,
        key: 'tin_no',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 21,
        label: 'CIN No',
        align: 'center',
        search: true,
        sort: true,
        stick: false,
        key: 'cin_no',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 22,
        label: 'FSSAI No',
        align: 'center',
        search: true,
        sort: true,
        stick: false,
        key: 'fssai_no',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 23,
        label: 'GST No',
        align: 'center',
        search: true,
        sort: true,
        stick: false,
        key: 'gst_no',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 24,
        label: 'Currency Code',
        align: 'center',
        search: true,
        sort: true,
        stick: false,
        key: 'currency_code',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 25,
        label: 'Agreement',
        align: 'center',
        search: true,
        sort: true,
        stick: false,
        key: 'agreement',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 26,
        label: 'Fields',
        align: 'center',
        search: true,
        sort: true,
        stick: false,
        key: 'fields',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 27,
        label: 'Confirmed',
        align: 'center',
        search: true,
        sort: true,
        stick: false,
        key: 'confirmed',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 28,
        label: 'Created By',
        align: 'center',
        search: true,
        sort: true,
        stick: false,
        key: 'created_by',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 30,
        label: 'Created At',
        align: 'center',
        search: true,
        sort: true,
        stick: false,
        key: 'created_at',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 29,
        label: 'Modified By',
        align: 'center',
        search: true,
        sort: true,
        stick: false,
        key: 'modified_by',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 31,
        label: 'Updated At',
        align: 'center',
        search: true,
        sort: true,
        stick: false,
        key: 'updated_at',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    }
]

export default headers
