/* eslint-disable */
import StatusBadge from '@core/components/StatusBadge'

export const locations = [
    {
        id: 1,
        name: 'John Doe',
        status: <StatusBadge type='success' label='Active' />,
        aadharCard: '1234-5678-9012',
        email: 'john.doe@example.com',
        createdBy: 'Alice Brown',
        createdAt: '14-11-2024 10:30',
    },
    {
        id: 2,
        name: 'Jane Smith',
        status: <StatusBadge type='danger' label='Inactive' />,
        aadharCard: '2345-6789-0123',
        email: 'jane.smith@example.com',
        createdBy: 'Bob White',
        createdAt: '13-11-2024 16:50',
    },
    {
        id: 3,
        name: 'Michael Brown',
        status: <StatusBadge type='success' label='Active' />,
        aadharCard: '3456-7890-1234',
        email: 'michael.brown@example.com',
        createdBy: 'Charlie Black',
        createdAt: '12-11-2024 13:20',
    },
    {
        id: 4,
        name: 'Emily Davis',
        status: <StatusBadge type='success' label='Active' />,
        aadharCard: '4567-8901-2345',
        email: 'emily.davis@example.com',
        createdBy: 'David Green',
        createdAt: '11-11-2024 09:10',
    },
    {
        id: 5,
        name: 'Chris Wilson',
        status: <StatusBadge type='success' label='Active' />,
        aadharCard: '5678-9012-3456',
        email: 'chris.wilson@example.com',
        createdBy: 'Eva White',
        createdAt: '10-11-2024 08:55',
    },
    {
        id: 6,
        name: 'Sophia Johnson',
        status: <StatusBadge type='danger' label='Inactive' />,
        aadharCard: '6789-0123-4567',
        email: 'sophia.johnson@example.com',
        createdBy: 'Frank Black',
        createdAt: '09-11-2024 12:25',
    },
    {
        id: 7,
        name: 'Daniel Martinez',
        status: <StatusBadge type='success' label='Active' />,
        aadharCard: '7890-1234-5678',
        email: 'daniel.martinez@example.com',
        createdBy: 'Grace Green',
        createdAt: '08-11-2024 17:40',
    },
    {
        id: 8,
        name: 'Olivia Garcia',
        status: <StatusBadge type='success' label='Active' />,
        aadharCard: '8901-2345-6789',
        email: 'olivia.garcia@example.com',
        createdBy: 'Hannah Red',
        createdAt: '07-11-2024 14:15',
    },
    {
        id: 9,
        name: 'Liam Miller',
        status: <StatusBadge type='success' label='Active' />,
        aadharCard: '9012-3456-7890',
        email: 'liam.miller@example.com',
        createdBy: 'Isaac Blue',
        createdAt: '06-11-2024 11:35',
    },
    {
        id: 10,
        name: 'Ava White',
        status: <StatusBadge type='danger' label='Inactive' />,
        aadharCard: '0123-4567-8901',
        email: 'ava.white@example.com',
        createdBy: 'Jack Yellow',
        createdAt: '05-11-2024 10:05',
    },
    {
        id: 11,
        name: 'Ethan Harris',
        status: <StatusBadge type='success' label='Active' />,
        aadharCard: '1234-5678-9012',
        email: 'ethan.harris@example.com',
        createdBy: 'Kathy Pink',
        createdAt: '04-11-2024 13:50',
    },
    {
        id: 12,
        name: 'Isabella Lee',
        status: <StatusBadge type='success' label='Active' />,
        aadharCard: '2345-6789-0123',
        email: 'isabella.lee@example.com',
        createdBy: 'Liam Brown',
        createdAt: '03-11-2024 15:30',
    }
]
