export const locations = [
    {
        id: '001',
        sku: 'UC0013',
        ean: '8904037200926',
        status: 'PICKED',
        desc: 'UCL',
        ordered: 4,
        pending: 0,
        confirm: 4,
        cancelled: 0,
        returned: 0,
        sale_amount: 3589,
        tax: 0,
        discount_amt: 0,
        shipping_charges: 0,
        final_amt: 3589
    },
    {
        id: '002',
        sku: 'FP3007',
        ean: '89040372019881',
        status: 'PICKED',
        desc: 'Penne Pasta',
        ordered: 3,
        pending: 1,
        confirm: 2,
        cancelled: 0,
        returned: 0,
        sale_amount: 1234,
        tax: 0,
        discount_amt: 0,
        shipping_charges: 0,
        final_amt: 1234
    },
    {
        id: '003',
        sku: 'FP3054',
        ean: '8904037200698',
        status: 'PACKED',
        desc: 'Mirch Powd',
        ordered: 3,
        pending: 0,
        confirm: 3,
        cancelled: 0,
        returned: 0,
        sale_amount: 7070,
        tax: 0,
        discount_amt: 0,
        shipping_charges: 0,
        final_amt: 7070
    },
    {
        id: '004',
        sku: 'HL1006',
        ean: '8904037212233',
        status: 'PACKED',
        desc: 'Krill Oil',
        ordered: 2,
        pending: 0,
        confirm: 2,
        cancelled: 0,
        returned: 0,
        sale_amount: 98.5,
        tax: 0,
        discount_amt: 0,
        shipping_charges: 0,
        final_amt: 98.5
    }
]

export const headers = [
    {
        id: 0,
        label: 'Sr.No',
        search: false,
        sort: false,
        stick: true,
        key: 's_no',
        isFrontend: true,
        visible: true,
        minWidth: 3.1,
        maxWidth: 3.1
    },
    { id: 1, label: 'SKU', key: 'sku', search: true, sort: true, visible: true, minWidth: 8, maxWidth: 8, stick: true },
    { id: 2, label: 'EAN', key: 'ean', search: true, sort: true, visible: true, minWidth: 8, maxWidth: 8, stick: true },
    {
        id: 3,
        label: 'Status',
        key: 'status',
        search: false,
        sort: false,
        visible: true,
        minWidth: 8,
        maxWidth: 8,
        stick: false
    },
    {
        id: 4,
        label: 'Description',
        key: 'desc',
        search: true,
        sort: true,
        visible: true,
        minWidth: 8,
        maxWidth: 8,
        stick: false
    },
    {
        id: 5,
        label: 'Ordered',
        key: 'ordered',
        search: true,
        sort: true,
        visible: true,
        minWidth: 8,
        maxWidth: 8,
        stick: false
    },
    {
        id: 6,
        label: 'Pending',
        key: 'pending',
        search: true,
        sort: true,
        visible: true,
        minWidth: 8,
        maxWidth: 8,
        stick: false
    },
    {
        id: 7,
        label: 'Confirm',
        key: 'confirm',
        search: true,
        sort: true,
        visible: true,
        minWidth: 8,
        maxWidth: 8,
        stick: false
    },
    {
        id: 8,
        label: 'Cancelled',
        key: 'cancelled',
        search: true,
        sort: true,
        visible: true,
        minWidth: 8,
        maxWidth: 8,
        stick: false
    },
    {
        id: 9,
        label: 'Returned',
        key: 'returned',
        search: true,
        sort: true,
        visible: true,
        minWidth: 8,
        maxWidth: 8,
        stick: false
    },
    {
        id: 10,
        label: 'Sale Amount',
        key: 'sale_amount',
        search: true,
        sort: true,
        visible: true,
        minWidth: 8,
        maxWidth: 8,
        stick: false
    },
    {
        id: 11,
        label: 'Tax %',
        key: 'tax',
        search: true,
        sort: true,
        visible: true,
        minWidth: 8,
        maxWidth: 8,
        stick: false
    },
    {
        id: 12,
        label: 'Discount Amt',
        key: 'discount_amt',
        search: true,
        sort: true,
        visible: true,
        minWidth: 8,
        maxWidth: 8,
        stick: false
    },
    {
        id: 13,
        label: 'Shipping Charges',
        key: 'shipping_charges',
        search: true,
        sort: true,
        visible: true,
        minWidth: 8,
        maxWidth: 8,
        stick: false
    },
    {
        id: 14,
        label: 'Final Amt',
        key: 'final_amt',
        search: true,
        sort: true,
        visible: true,
        minWidth: 8,
        maxWidth: 8,
        stick: false
    }
]
