export const locations = [
    {
        id: 1,
        orderId: 'VYP049008',
        packId: 'PKID-01',
        orderType: 'B2B',
        status: 'In Progress',
        channel: 'Flipkart',
        courier: 'Delhivery',
        awbNo: '49008',
        totalBoxes: 1,
        totalWeight: '0.25',
        tableId: 'A1',
        createdBy: 'Rahul Sharma',
        modifiedBy: 'Amit Verma',
        createdAt: '06-09-2024 12:30',
        modifiedAt: '06-09-2024 12:41'
    },
    {
        id: 2,
        orderId: 'VYP049009',
        packId: 'PKID-02',
        orderType: 'Returnable Challan',
        status: 'In Progress',
        channel: 'Amazon',
        courier: 'FedEx',
        awbNo: '49009',
        totalBoxes: 1,
        totalWeight: '0.25',
        tableId: 'A2',
        createdBy: 'Priya Kapoor',
        modifiedBy: 'Rahul Sharma',
        createdAt: '06-09-2024 12:32',
        modifiedAt: '06-09-2024 12:42'
    },
    {
        id: 3,
        orderId: 'VYP049010',
        packId: 'PKID-03',
        orderType: 'B2C',
        status: 'In Progress',
        channel: 'Myntra',
        courier: 'BlueDart',
        awbNo: '49010',
        totalBoxes: 1,
        totalWeight: '0.25',
        tableId: 'A3',
        createdBy: 'Younis Ibni Ismael',
        modifiedBy: 'Priya Kapoor',
        createdAt: '06-09-2024 12:34',
        modifiedAt: '06-09-2024 12:43'
    },
    {
        id: 4,
        orderId: 'VYP049011',
        packId: 'PKID-04',
        orderType: 'B2B',
        status: 'In Progress',
        channel: 'Flipkart',
        courier: 'Ecom Express',
        awbNo: '49011',
        totalBoxes: 1,
        totalWeight: '0.25',
        tableId: 'A4',
        createdBy: 'Amit Verma',
        modifiedBy: 'Rahul Sharma',
        createdAt: '06-09-2024 12:36',
        modifiedAt: '06-09-2024 12:44'
    },
    {
        id: 5,
        orderId: 'VYP049012',
        packId: 'PKID-05',
        orderType: 'Purchase Return',
        status: 'Packed',
        channel: 'Amazon',
        courier: 'Delhivery',
        awbNo: '49012',
        totalBoxes: 1,
        totalWeight: '0.25',
        tableId: 'A5',
        createdBy: 'Rahul Sharma',
        modifiedBy: 'Younis Ibni Ismael',
        createdAt: '06-09-2024 12:38',
        modifiedAt: '06-09-2024 12:45'
    },
    {
        id: 6,
        orderId: 'VYP049013',
        packId: 'PKID-06',
        orderType: 'B2C',
        status: 'In Progress',
        channel: 'Myntra',
        courier: 'FedEx',
        awbNo: '49013',
        totalBoxes: 1,
        totalWeight: '0.25',
        tableId: 'A6',
        createdBy: 'Priya Kapoor',
        modifiedBy: 'Amit Verma',
        createdAt: '06-09-2024 12:40',
        modifiedAt: '06-09-2024 12:46'
    },
    {
        id: 7,
        orderId: 'VYP049014',
        packId: 'PKID-07',
        orderType: 'B2B',
        status: 'In Progress',
        channel: 'Flipkart',
        courier: 'BlueDart',
        awbNo: '49014',
        totalBoxes: 1,
        totalWeight: '0.25',
        tableId: 'A7',
        createdBy: 'Younis Ibni Ismael',
        modifiedBy: 'Priya Kapoor',
        createdAt: '06-09-2024 12:42',
        modifiedAt: '06-09-2024 12:47'
    },
    {
        id: 8,
        orderId: 'VYP049015',
        packId: 'PKID-08',
        orderType: 'Non-Returnable Challan',
        status: 'Packed',
        channel: 'Amazon',
        courier: 'Ecom Express',
        awbNo: '49015',
        totalBoxes: 1,
        totalWeight: '0.25',
        tableId: 'A8',
        createdBy: 'Amit Verma',
        modifiedBy: 'Rahul Sharma',
        createdAt: '06-09-2024 12:44',
        modifiedAt: '06-09-2024 12:48'
    },
    {
        id: 9,
        orderId: 'VYP049016',
        packId: 'PKID-09',
        orderType: 'B2C',
        status: 'Packed',
        channel: 'Myntra',
        courier: 'Delhivery',
        awbNo: '49016',
        totalBoxes: 1,
        totalWeight: '0.25',
        tableId: 'A9',
        createdBy: 'Rahul Sharma',
        modifiedBy: 'Younis Ibni Ismael',
        createdAt: '06-09-2024 12:46',
        modifiedAt: '06-09-2024 12:49'
    },
    {
        id: 10,
        orderId: 'VYP049017',
        packId: 'PKID-10',
        orderType: 'STO',
        status: 'Packed',
        channel: 'Odessey',
        courier: 'FedEx',
        awbNo: '49017',
        totalBoxes: 10,
        totalWeight: '30',
        tableId: 'A10',
        createdBy: 'Priya Kapoor',
        modifiedBy: 'Amit Verma',
        createdAt: '06-09-2024 12:48',
        modifiedAt: '06-09-2024 12:50'
    },
    {
        id: 11,
        orderId: 'VYP049018',
        packId: 'PKID-11',
        orderType: 'Promotion',
        status: 'In Progress',
        channel: 'Flipkart',
        courier: 'BlueDart',
        awbNo: '49018',
        totalBoxes: 2,
        totalWeight: '1.50',
        tableId: 'A11',
        createdBy: 'Younis Ibni Ismael',
        modifiedBy: 'Priya Kapoor',
        createdAt: '06-09-2024 12:50',
        modifiedAt: '06-09-2024 12:51'
    },
    {
        id: 12,
        orderId: 'VYP049019',
        packId: 'PKID-12',
        orderType: 'Job Work',
        status: 'Packed',
        channel: 'Amazon',
        courier: 'Ecom Express',
        awbNo: '49019',
        totalBoxes: 3,
        totalWeight: '2.00',
        tableId: 'A12',
        createdBy: 'Amit Vermaaaaaaaaaaaaa',
        modifiedBy: 'Rahul Sharma',
        createdAt: '06-09-2024 12:52',
        modifiedAt: '06-09-2024 12:52'
    }
]

export const headers = [
    {
        id: 99,
        label: 'Sr. No.',
        isFrontend: true,
        search: false,
        sort: false,
        stick: true,
        key: 's_no',
        visible: true,
        minWidth: 3.25,
        maxWidth: 3.25
    },
    {
        id: 20,
        label: 'Pack Id',
        search: true,
        sort: true,
        key: 'no',
        visible: true,
        stick: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 22,
        label: 'Order Id',
        search: true,
        sort: true,
        key: 'order_no',
        visible: true,
        stick: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 27,
        label: 'Status',
        search: false,
        sort: false,
        filter: true,
        options: ['In Progress', 'Packed'],
        key: 'status',
        visible: true,
        stick: true,
        minWidth: 11,
        maxWidth: 11
    },
    {
        id: 1,
        label: 'Order Type',
        search: false,
        sort: false,
        filter: true,
        options: [
            'B2B',
            'STO',
            'Returnable Challan',
            'Non-Returnable Challan',
            'Purchase Return',
            'Job Work',
            'B2C',
            'Exchange',
            'Sample',
            'Promotion'
        ],
        key: 'order_type',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    { id: 2, label: 'Channel', search: true, sort: true, key: 'channel_code', visible: true, minWidth: 8, maxWidth: 8 },
    {
        id: 8,
        label: 'Courier Name',
        search: true,
        sort: true,
        key: 'courier_code',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    { id: 4, label: 'AWB No.', search: true, sort: true, key: 'awb_no', visible: true, minWidth: 8, maxWidth: 8 },
    {
        id: 5,
        label: 'Total Boxes',
        search: true,
        sort: true,
        key: 'box_count',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 3,
        label: 'Total Weight (Kg)',
        search: true,
        sort: true,
        key: 'actual_weight',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    // { id: 9, label: 'Table Id', search: true, sort: true, key: 'tableId', visible: true, minWidth: 8, maxWidth: 8 },
    {
        id: 10,
        label: 'Created By',
        search: true,
        sort: true,
        key: 'created_by',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 9,
        label: 'Created At',
        search: true,
        sort: true,
        key: 'created_at',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 19,
        label: 'Modified By',
        search: true,
        sort: true,
        key: 'modified_by',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 29,
        label: 'Modified At',
        search: true,
        sort: true,
        key: 'updated_at',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    }
]
