/* eslint-disable */
import StatusBadge from '@core/components/StatusBadge'

export const locations = [
    {
        id: 1,
        locationCode: 'LOC001',
        zone: 'Zone A',
        storageType: 'Pallet',
        inventoryType: <StatusBadge type='success' label='Good' />,
        ExtBucket: 'Bucket-01',
        status: <StatusBadge type='danger' label='# N/A' />,
        distance: 10,
        volumeCapacity: 100,
        weightCapacity: 500,
        dimensions: '2x1.5x2',
        floor: 1,
        aisle: 'Aisle-01',
        rack: 'Rack-01',
        bay: 'Bay-01',
        level: 2,
        position: 'P-01',
        sequence: 1,
        priority: 'High',
        createdBy: 'John Doe',
        createdAt: '14-11-2024 10:30',
        updatedBy: 'Jane Smith',
        updatedAt: '15-11-2024 12:00'
    },
    {
        id: 2,
        locationCode: 'LOC002',
        zone: 'Zone B',
        storageType: 'Bin',
        inventoryType: <StatusBadge type='danger' label='Bad' />,
        ExtBucket: 'Bucket-02',
        status: <StatusBadge type='success' label='Available' />,
        distance: 15,
        volumeCapacity: 50,
        weightCapacity: 200,
        dimensions: '1x1x1.5',
        floor: 2,
        aisle: 'Aisle-02',
        rack: 'Rack-02',
        bay: 'Bay-02',
        level: 1,
        position: 'P-02',
        sequence: 2,
        priority: 'Medium',
        createdBy: 'Jane Smith',
        createdAt: '12-11-2024 09:00',
        updatedBy: 'John Doe',
        updatedAt: '15-11-2024 11:00'
    },
    {
        id: 3,
        locationCode: 'LOC003',
        zone: 'Zone C',
        storageType: 'Pallet',
        inventoryType: <StatusBadge type='success' label='Good' />,
        ExtBucket: 'Bucket-03',
        status: <StatusBadge type='danger' label='# N/A' />,
        distance: 20,
        volumeCapacity: 120,
        weightCapacity: 600,
        dimensions: '2.5x2x2',
        floor: 1,
        aisle: 'Aisle-03',
        rack: 'Rack-03',
        bay: 'Bay-03',
        level: 3,
        position: 'P-03',
        sequence: 3,
        priority: 'High',
        createdBy: 'Alice Johnson',
        createdAt: '10-11-2024 08:00',
        updatedBy: 'Jane Smith',
        updatedAt: '15-11-2024 10:30'
    },
    {
        id: 4,
        locationCode: 'LOC004',
        zone: 'Zone D',
        storageType: 'Bin',
        inventoryType: <StatusBadge type='success' label='Good' />,
        ExtBucket: 'Bucket-04',
        status: <StatusBadge type='success' label='Available' />,
        distance: 12,
        volumeCapacity: 80,
        weightCapacity: 300,
        dimensions: '1.5x1.2x1.8',
        floor: 2,
        aisle: 'Aisle-04',
        rack: 'Rack-04',
        bay: 'Bay-04',
        level: 2,
        position: 'P-04',
        sequence: 4,
        priority: 'Medium',
        createdBy: 'John Doe',
        createdAt: '09-11-2024 14:20',
        updatedBy: 'Jane Smith',
        updatedAt: '15-11-2024 13:15'
    },
    {
        id: 5,
        locationCode: 'LOC005',
        zone: 'Zone E',
        storageType: 'Bin',
        inventoryType: <StatusBadge type='danger' label='Bad' />,
        ExtBucket: 'Bucket-05',
        status: <StatusBadge type='danger' label='# N/A' />,
        distance: 18,
        volumeCapacity: 40,
        weightCapacity: 150,
        dimensions: '1x1x1.2',
        floor: 1,
        aisle: 'Aisle-05',
        rack: 'Rack-05',
        bay: 'Bay-05',
        level: 1,
        position: 'P-05',
        sequence: 5,
        priority: 'Low',
        createdBy: 'Jane Smith',
        createdAt: '11-11-2024 11:15',
        updatedBy: 'John Doe',
        updatedAt: '15-11-2024 14:10'
    },
    {
        id: 6,
        locationCode: 'LOC006',
        zone: 'Zone F',
        storageType: 'Pallet',
        inventoryType: <StatusBadge type='success' label='Good' />,
        ExtBucket: 'Bucket-06',
        status: <StatusBadge type='success' label='Available' />,
        distance: 25,
        volumeCapacity: 200,
        weightCapacity: 800,
        dimensions: '3x2.5x2.2',
        floor: 3,
        aisle: 'Aisle-06',
        rack: 'Rack-06',
        bay: 'Bay-06',
        level: 4,
        position: 'P-06',
        sequence: 6,
        priority: 'High',
        createdBy: 'Alice Johnson',
        createdAt: '10-11-2024 15:10',
        updatedBy: 'Jane Smith',
        updatedAt: '15-11-2024 16:30'
    },
    {
        id: 7,
        locationCode: 'LOC007',
        zone: 'Zone G',
        storageType: 'Pallet',
        inventoryType: <StatusBadge type='success' label='Good' />,
        ExtBucket: 'Bucket-07',
        status: <StatusBadge type='danger' label='# N/A' />,
        distance: 22,
        volumeCapacity: 150,
        weightCapacity: 700,
        dimensions: '2.8x2x2.5',
        floor: 1,
        aisle: 'Aisle-07',
        rack: 'Rack-07',
        bay: 'Bay-07',
        level: 3,
        position: 'P-07',
        sequence: 7,
        priority: 'High',
        createdBy: 'Jane Smith',
        createdAt: '12-11-2024 10:00',
        updatedBy: 'John Doe',
        updatedAt: '15-11-2024 14:20'
    },
    {
        id: 8,
        locationCode: 'LOC008',
        zone: 'Zone H',
        storageType: 'Bin',
        inventoryType: <StatusBadge type='success' label='Good' />,
        ExtBucket: 'Bucket-08',
        status: <StatusBadge type='success' label='Available' />,
        distance: 30,
        volumeCapacity: 90,
        weightCapacity: 400,
        dimensions: '1.8x1.2x1.5',
        floor: 2,
        aisle: 'Aisle-08',
        rack: 'Rack-08',
        bay: 'Bay-08',
        level: 2,
        position: 'P-08',
        sequence: 8,
        priority: 'Medium',
        createdBy: 'Alice Johnson',
        createdAt: '09-11-2024 14:00',
        updatedBy: 'Jane Smith',
        updatedAt: '15-11-2024 16:00'
    },
    {
        id: 9,
        locationCode: 'LOC009',
        zone: 'Zone I',
        storageType: 'Bin',
        inventoryType: <StatusBadge type='danger' label='Bad' />,
        ExtBucket: 'Bucket-09',
        status: <StatusBadge type='danger' label='# N/A' />,
        distance: 28,
        volumeCapacity: 60,
        weightCapacity: 250,
        dimensions: '1.2x1.1x1.3',
        floor: 3,
        aisle: 'Aisle-09',
        rack: 'Rack-09',
        bay: 'Bay-09',
        level: 1,
        position: 'P-09',
        sequence: 9,
        priority: 'Low',
        createdBy: 'John Doe',
        createdAt: '08-11-2024 11:45',
        updatedBy: 'Jane Smith',
        updatedAt: '15-11-2024 14:45'
    },
    {
        id: 10,
        locationCode: 'LOC010',
        zone: 'Zone J',
        storageType: 'Pallet',
        inventoryType: <StatusBadge type='success' label='Good' />,
        ExtBucket: 'Bucket-10',
        status: <StatusBadge type='success' label='Available' />,
        distance: 35,
        volumeCapacity: 220,
        weightCapacity: 900,
        dimensions: '3x2.7x2.3',
        floor: 4,
        aisle: 'Aisle-10',
        rack: 'Rack-10',
        bay: 'Bay-10',
        level: 5,
        position: 'P-10',
        sequence: 10,
        priority: 'High',
        createdBy: 'Alice Johnson',
        createdAt: '11-11-2024 12:30',
        updatedBy: 'Jane Smith',
        updatedAt: '15-11-2024 15:45'
    }
]

export const headers = [
    {
        id: 0,
        label: 'Sr. No.',
        align: 'center',
        search: false,
        sort: false,
        stick: true,
        key: 's_no',
        isFrontend: true,
        visible: true,
        minWidth: 3.187,
        maxWidth: 3.187
    },
    {
        id: 1,
        label: 'Code',
        search: true,
        sort: true,
        stick: true,
        key: 'code',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 4,
        label: 'Zone',
        search: true,
        sort: true,
        stick: true,
        key: 'storage_zone_code',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 5,
        label: 'Storage Type',
        search: true,
        sort: false,
        stick: false,
        key: 'storage_type',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 6,
        label: 'Inventory Type',
        search: true,
        sort: false,
        stick: false,
        key: 'inventory_type',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 7,
        label: 'Ext Bucket',
        search: true,
        sort: false,
        stick: false,
        key: 'bucket',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 8,
        label: 'Priority',
        search: false,
        sort: true,
        stick: false,
        key: 'priority',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 9,
        label: 'Floor',
        search: true,
        sort: false,
        stick: false,
        key: 'floor',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 10,
        label: 'Aisle',
        search: true,
        sort: false,
        stick: false,
        key: 'aisle',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 11,
        label: 'Rack',
        search: true,
        sort: false,
        stick: false,
        key: 'rack',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 12,
        label: 'Bay',
        search: true,
        sort: false,
        stick: false,
        key: 'bay',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 13,
        label: 'Level',
        search: true,
        sort: false,
        stick: false,
        key: 'level',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 14,
        label: 'Position',
        search: true,
        sort: false,
        stick: false,
        key: 'position',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 15,
        label: 'Length',
        search: false,
        sort: false,
        stick: false,
        key: 'length',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 16,
        label: 'Breadth',
        search: false,
        sort: false,
        stick: false,
        key: 'breadth',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 17,
        label: 'Height',
        search: false,
        sort: false,
        stick: false,
        key: 'height',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 18,
        label: 'Sequence',
        search: false,
        sort: false,
        stick: false,
        key: 'sequence',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 19,
        label: 'Distance',
        search: false,
        sort: false,
        stick: false,
        key: 'distance',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 20,
        label: 'Vol. Capacity',
        search: false,
        sort: false,
        stick: false,
        key: 'vol_capacity',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 21,
        label: 'Weight Capacity',
        search: false,
        sort: false,
        stick: false,
        key: 'weight_capacity',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 22,
        label: 'Status',
        search: false,
        sort: false,
        stick: false,
        key: 'status',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 23,
        label: 'Movement Allowed',
        search: false,
        sort: false,
        stick: false,
        key: 'movement_allowed',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    // {
    //     id: 24,
    //     label: 'Reserved',
    //     search: false,
    //     sort: false,
    //     stick: false,
    //     key: 'reserved',
    //     visible: true,
    //     minWidth: 8,
    //     maxWidth: 8
    // },
    {
        id: 27,
        label: 'Created At',
        search: false,
        sort: false,
        stick: false,
        key: 'created_at',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 25,
        label: 'Created By',
        search: false,
        sort: false,
        stick: false,
        key: 'created_by',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 26,
        label: 'Modified By',
        search: false,
        sort: false,
        stick: false,
        key: 'modified_by',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 28,
        label: 'Updated At',
        search: false,
        sort: false,
        stick: false,
        key: 'updated_at',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    }
]

export const STATUS_TYPE = {
    0: {
        label: '# N/A',
        color: 'danger'
    },
    1: {
        label: 'Available',
        color: 'success'
    }
}

export const TYPE_COLOR = {
    BAD: 'danger',
    REJECTED: 'danger',
    MISSING: 'danger',
    CANCEL: 'info',
    EXCESS: 'info',
    SUSPENSE: 'info',
    GOOD: 'success'
}
