/* eslint-disable */

export const locations = [
    {
        id: 1,
        refNo: 'VEN001',
        name: 'Amit Sharma',
        code: '110021',
        pincode: '110021',
        shipToAddress: 'Dwarka',
        contactNo: '9876543210',
        email: 'amit.sharma@example.com',
        GSTIN: '22ABCDE1234F1Z5',
        PAN: 'ABCDE1234F',
        createdBy: 'Rohit Singh',
        createdAt: '12-08-2024 09:15',
        modifiedBy: 'Sneha Verma',
        modifiedAt: '14-10-2024 14:32'
    },
    {
        id: 2,
        refNo: 'VEN002',
        name: 'Neha Gupta',
        code: '110045',
        pincode: '110045',
        shipToAddress: 'Rajouri Garden',
        contactNo: '9123456789',
        email: 'neha.gupta@example.com',
        GSTIN: '22ABCDE1234F1Z5',
        PAN: 'XYZEF9876T',
        createdBy: 'Arjun Mehta',
        createdAt: '07-07-2024 11:00',
        modifiedBy: 'Karan Malhotra',
        modifiedAt: '18-09-2024 10:20'
    },
    {
        id: 3,
        refNo: 'VEN003',
        name: 'Rahul Kapoor',
        code: '110034',
        pincode: '110034',
        shipToAddress: 'Punjabi Bagh',
        contactNo: '8293456712',
        email: 'rahul.kapoor@example.com',
        GSTIN: '22ABCDE1234F1Z5',
        PAN: 'LMNOP4567D',
        createdBy: 'Manish Tiwari',
        createdAt: '01-05-2024 15:45',
        modifiedBy: 'Aditi Joshi',
        modifiedAt: '22-11-2024 17:10'
    },
    {
        id: 4,
        refNo: 'VEN004',
        name: 'Priya Jain',
        code: '110056',
        pincode: '110056',
        shipToAddress: 'Karol Bagh',
        contactNo: '7896543210',
        email: 'priya.jain@example.com',
        GSTIN: '22ABCDE1234F1Z5',
        PAN: 'QRSTU7890K',
        createdBy: 'Vikram Rao',
        createdAt: '15-03-2024 13:25',
        modifiedBy: 'Megha Sharma',
        modifiedAt: '30-10-2024 09:40'
    },
    {
        id: 5,
        refNo: 'VEN005',
        name: 'Rohan Mishra',
        code: '110067',
        pincode: '110067',
        shipToAddress: 'Vasant Kunj',
        contactNo: '9128675309',
        email: 'rohan.mishra@example.com',
        GSTIN: '22ABCDE1234F1Z5',
        PAN: 'UVWXY6789P',
        createdBy: 'Pooja Gupta',
        createdAt: '20-06-2024 12:05',
        modifiedBy: 'Rajat Verma',
        modifiedAt: '03-10-2024 16:50'
    },
    {
        id: 6,
        refNo: 'VEN006',
        name: 'Anjali Verma',
        code: '110078',
        pincode: '110078',
        shipToAddress: 'Janakpuri',
        contactNo: '9012345678',
        email: 'anjali.verma@example.com',
        GSTIN: '22ABCDE1234F1Z5',
        PAN: 'ABCDE2345R',
        createdBy: 'Ankur Bhatia',
        createdAt: '28-02-2024 14:20',
        modifiedBy: 'Sonia Chawla',
        modifiedAt: '08-07-2024 19:15'
    },
    {
        id: 7,
        refNo: 'VEN007',
        name: 'Manoj Desai',
        code: '110022',
        pincode: '110022',
        shipToAddress: 'Green Park',
        contactNo: '9456789012',
        email: 'manoj.desai@example.com',
        GSTIN: '22ABCDE1234F1Z5',
        PAN: 'LMNOP8901C',
        createdBy: 'Deepak Malhotra',
        createdAt: '11-04-2024 10:45',
        modifiedBy: 'Kavita Yadav',
        modifiedAt: '25-08-2024 13:55'
    },
    {
        id: 8,
        refNo: 'VEN008',
        name: 'Kiran Rao',
        code: '110024',
        pincode: '110024',
        shipToAddress: 'Hauz Khas',
        contactNo: '9834512678',
        email: 'kiran.rao@example.com',
        GSTIN: '22ABCDE1234F1Z5',
        PAN: 'XYZEF2345X',
        createdBy: 'Siddharth Jain',
        createdAt: '03-03-2024 08:30',
        modifiedBy: 'Meera Patil',
        modifiedAt: '19-11-2024 12:40'
    },
    {
        id: 9,
        refNo: 'VEN009',
        name: 'Shweta Mehta',
        code: '110019',
        pincode: '110019',
        shipToAddress: 'Lajpat Nagar',
        contactNo: '9654321890',
        email: 'shweta.mehta@example.com',
        GSTIN: '22ABCDE1234F1Z5',
        PAN: 'QRSTU1234Q',
        createdBy: 'Nikhil Arora',
        createdAt: '14-01-2024 17:20',
        modifiedBy: 'Geeta Kapoor',
        modifiedAt: '29-09-2024 11:50'
    },
    {
        id: 10,
        refNo: 'VEN010',
        name: 'Vivek Singh',
        code: '110055',
        pincode: '110055',
        shipToAddress: 'Connaught Place',
        contactNo: '9876501234',
        email: 'vivek.singh@example.com',
        GSTIN: '22ABCDE1234F1Z5',
        PAN: 'UVWXY5678L',
        createdBy: 'Ramesh Kumar',
        createdAt: '19-05-2024 09:50',
        modifiedBy: 'Sheetal Nair',
        modifiedAt: '12-08-2024 18:10'
    }
]

export const headers = [
    {
        id: 0,
        label: 'Sr. No.',
        search: false,
        sort: false,
        stick: true,
        key: 's_no',
        isFrontend: true,
        visible: true,
        minWidth: 3.1,
        maxWidth: 3.1,
        align: 'center'
    },
    {
        id: 1,
        label: 'Ref No.',
        search: true,
        sort: false,
        stick: true,
        key: 'refNo',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 2,
        label: 'Name',
        search: true,
        sort: false,
        stick: true,
        key: 'name',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 3,
        label: 'Code',
        search: true,
        sort: false,
        stick: false,
        key: 'code',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 4,
        label: 'Shipping Pincode',
        search: true,
        sort: false,
        stick: false,
        key: 'ship_pincode',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 5,
        label: 'Address',
        search: false,
        sort: false,
        stick: false,
        key: 'address',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 6,
        label: 'Contact No',
        search: true,
        sort: false,
        stick: false,
        key: 'contact_no',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 7,
        label: 'Email',
        search: true,
        sort: false,
        stick: false,
        key: 'email',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 8,
        label: 'GST No.',
        search: true,
        sort: false,
        stick: false,
        key: 'gst_in',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    },
    {
        id: 9,
        label: 'PAN No.',
        search: true,
        sort: false,
        stick: false,
        key: 'pan_no',
        visible: true,
        minWidth: 8,
        maxWidth: 8
    }
]
